### ISSUE TITLE
Error in my code, but your demo working: codeError: Cannot read properties of undefined (reading 'order')

### ISSUE THREAD

**Issue by diegomca** [pipipi-pikachu/pptx2json#11]
Hi! Thank you for this package, you don't know how much you have saved me for a project that I need to start analyzing a .pptx from scratch. But I have a error. (it should be noted that there are slides that give me the JSON, but there are others that I have a similar problem)

In your demo that you deliver, I upload a pptx that gives me an error in my code, but in your demo it does work. And I have made the script just like the example and there are PPTX that do work in my algorithm.

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'order')
     at index.js:8333:1
     at Array.sort (<anonymous>)
     at Uh (index.js:8332:1)
     at zh (index.js:7991:1)
     at Lh (index.js:7946:1)
     at index.js:7850:1
     at d (index.js:112:1)
     at Generator.<anonymous> (index.js:193:1)
     at Generator.next (index.js:137:1)
     at e (index.js:10:1)
```

My question is: What must it be that in your environment you deliver it to me in a good way and in my local environment you don't? Any package missing from package.json?

**Comment by diegomca** [comment]
Looking at your code, I think the error is on line 838 of the pptxtojson.js file

```
  if (brNode.length > 1) brNode.shift()
        rNode = rNode.concat(brNode)
        rNode.sort((a, b) => {
          if (!a.attrs || !b.attrs) return true
          return a.attrs.order - b.attrs.order
        })
      }
```

**Comment by pipipi-pikachu** [comment]
> Because the version on npm is different from the version in the demo. I have now published the latest version. You can try again.

You need to update to the latest version I just released.

**Comment by diegomca** [comment]
It works now, you are god. Ask, Do you know or do you have any package to read the json file? I'm actually doing it, it's nothing complicated, just time. But I wanted to know if there was anything already to use.

**Comment by pipipi-pikachu** [comment]
Sorry, I don't understand what you mean...
If the JSON file is from the internet, we can easily use an AJAX GET request to fetch it, isn't it?
And if you need to read a locally uploaded file, you can use the FileReader API
