### ISSUE TITLE
slideFactor的转换因子原理是什么？

### ISSUE THREAD

**Issue by YiJieZheng** [pipipi-pikachu/pptx2json#13]
我在将pptx转换为json后，对其进行一些编辑，再通过修改后的json转换回pptx时，幻灯片的画布大小与未修改的pptx画布大小不一致，导致ppt布局错乱

**Comment by pipipi-pikachu** [comment]
这个原理我并不太清楚，现在的参数是我参考其他工具的，但可以确定的是这个值在不同的设备上应该是不同的，而且我目前也还不清楚有什么方式可以从浏览器端拿到这个比值。
所以你说的这个问题只能考虑后续版本添加配置，支持导出原单位（英寸、磅）也许会有一些帮助。
