### ISSUE TITLE
导出来的json数据，svg数据好像不完善，无法转成有效的图形

### ISSUE THREAD

**Issue by shufan209** [pipipi-pikachu/pptx2json#2]
如题
![360截图20230218114355003](https://user-images.githubusercontent.com/12206238/219829800-adca9d0b-00b8-4972-b394-1b802eb8bccf.png)

**Comment by pipipi-pikachu** [comment]
目前没有计划将形状导出为SVG，如果你有这个需求，可以参考 [PPTXjs](https://github.com/meshesha/PPTXjs) 来实现。
这里没有去实现这个主要的原因是工作量太大了，其次是本仓库作为 [PPTist](https://github.com/pipipi-pikachu/PPTist)的一个附属项目，计划是后面在PPTist中实现形状，然后用导出的shapeType字段来做映射并渲染。
