### ISSUE TITLE
图形转web格式

### ISSUE THREAD

**Issue by shufan209** [pipipi-pikachu/pptx2json#3]
参考下这个工具  ：http://viewer.flyfish.group/ 
我使用wps上的图形都完美转web格式了。
[基本图形例子](http://sitebackup.wedlaa.com/wps%E4%B8%8A%E7%9A%84%E5%9F%BA%E6%9C%AC%E5%9B%BE%E5%BD%A2.pptx)
要不下载这个基本图形例子测试下？
所以读取pptx的xml数据，能生成有效的web图形数据

**Comment by pipipi-pikachu** [comment]
...当然可以转换SVG的啊，只是现在不打算去做这个事，具体原因在 #2  这条issue中已经说过了。前面也已经说了可以参考 https://github.com/meshesha/PPTXjs 这个仓库来实现，你上面的工具就是基于它来做的，对比一下生成的形状数据就知道了。

甚至如果对数据要求不高的，直接copy一下就能拿来用了。
